# Generated by Django 2.2.1 on 2019-05-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, unique=True)),
                ('classe', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='estilo_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokedex.EstiloCard', verbose_name='Estilo CSS do card'),
        ),
    ]
